apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: k8s-metrics-cpu
spec:
  template:
    spec:
      containers:
      - name: k8s-metrics-cpu
        image: registry.cn-hangzhou.aliyuncs.com/vikinglion/k8s-metrics-cpu:latest
        imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-cpa
  roleRequiresMetricsServer: true
  config:
    - name: interval
      value: "10000"
    - name: downscaleStabilization
      value: "60"
