apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      name: load-generator
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: busybox
        command:
        - /bin/sh
        - -c
        # send request to php-hpa and php-cpa respectively through ClusterIP
        - "while sleep 0.1; do wget -q -O- http://10.108.79.37:80; wget -q -O- http://10.96.52.59:80; done"
